### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Luongzz** [0xCyll/valorant-tracking-bot#1]
`[2023-08-14 19:56:46] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command track_user
Traceback (most recent call last):
  File "C:\Users\Yoshino\Desktop\Bot\bot discord\game\valorant-tracking-bot-main\main.py", line 107, in track_user
    tracked_users = json.load(f)
                    ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
io.UnsupportedOperation: not readable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yoshino\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoshino\Desktop\Bot\bot discord\game\valorant-tracking-bot-main\main.py", line 113, in track_user
    await logger(traceback.format_exc())
  File "C:\Users\Yoshino\Desktop\Bot\bot discord\game\valorant-tracking-bot-main\main.py", line 45, in logger
    await channel.send(message)
          ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Yoshino\AppData\Roaming\Python\Python311\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoshino\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'track_user' raised an exception: AttributeError: 'NoneType' object has no attribute 'send'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Yoshino\AppData\Roaming\Python\Python311\site-packages\discord\ext\commands\hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoshino\AppData\Roaming\Python\Python311\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'track_user' raised an exception: AttributeError: 'NoneType' object has no attribute 'send'`

**Comment by 0xCyll** [comment]
My apologies, I have updated the code and made a new release this should hopefully fix the bugs you faced.
