### ISSUE TITLE
Can you add the feature to delete the name of the person you are tracking?

### ISSUE THREAD

**Issue by Luongzz** [0xCyll/valorant-tracking-bot#5]

**Comment by 0xCyll** [comment]
I will slowly work on this, but it wont be done fast as i am busy with exams, sorry.

**Comment by 0xCyll** [comment]
i did it dont have time to test im afraid, if it doesnt work let me know.

**Comment by Luongzz** [comment]
> i did it dont have time to test im afraid, if it doesnt work let me know.

@bot.hybrid_command not @bot.hybrid.command

**Comment by 0xCyll** [comment]
oops my bad

**Comment by Luongzz** [comment]
> oops my bad

```
2023-09-30 11:15:43 ERROR    discord.ext.commands.bot Ignoring exception in command remove
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/main.py", line 126, in tracker_remove
    if username not in tracked_users['username']:
                       ~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'username'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'remove' raised an exception: KeyError: 'username'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'remove' raised an exception: KeyError: 'username'
```

**Comment by Luongzz** [comment]
Looks like there's a query problem

**Comment by Luongzz** [comment]
![image](https://github.com/0xCyll/valorant-tracking-bot/assets/37655807/0ed94558-6cc3-46cb-adb0-9e0c92307722)
I fixed it a bit but it still doesn't seem to work

**Comment by 0xCyll** [comment]
i accidentally put 'username' into the field when it should be just username, test now?

**Comment by Luongzz** [comment]
> i accidentally put 'username' into the field when it should be just username, test now?

How do I need to change?

**Comment by 0xCyll** [comment]
you can redownloadmain.py or  change the remove command into this
```
@bot.hybrid_command(name='remove',` description="Remove a user from the tracker, input username not tag", with_app_command=True)
async def tracker_remove(ctx, username: str,):

        if username not in tracked_users[username]:
            return await ctx.send('User is not currently being tracked.', ephemeral=True)

        del tracked_users[username]

        await ctx.send(f'Stopped tracking {username}.')

**Comment by Luongzz** [comment]
> you can redownloadmain.py or change the remove command into this
> 
> ```
> @bot.hybrid_command(name='remove',` description="Remove a user from the tracker, input username not tag", with_app_command=True)
> async def tracker_remove(ctx, username: str,):
> 
>         if username not in tracked_users[username]:
>             return await ctx.send('User is not currently being tracked.', ephemeral=True)
> 
>         del tracked_users[username]
> 
>         await ctx.send(f'Stopped tracking {username}.')
> ```

it looks like it's still the same

**Comment by 0xCyll** [comment]
it looks the same but i changed the tracked_users query, do you still get the same error?

**Comment by Luongzz** [comment]
> it looks the same but i changed the tracked_users query, do you still get the same error?

yes

**Comment by 0xCyll** [comment]
damn then i dont really have a clue at the moment, give me a few hours and ill come back to this

**Comment by Luongzz** [comment]
Although the code still works, slash cannot be used

**Comment by 0xCyll** [comment]
Hey so i know this is impractical, but i have a version of this bot perma hosted with slightly different code. and inside it i have added the remove command that actually works, so if you want to use that as a solution you can. The invite link is at the top of the readme
